# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e69f69adca6f23d5ae80bad3f25e7f8365e2cc096a4931aac728623f7e042459fb272c0c07ea4b878dd66582bd4edd557bc6b9993d3b3537749bf9227c690e19

test:
  secret_key_base: 3e91ad56a5b99860c61c48011bc52708baaa0dc130d889cbd906cf849ad3c7548aaf42da3d27ab3132110cb7b3d146f0e3b9a6744cd549b116f8da4d8460f9f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
